# Generated by Django 5.1.1 on 2024-09-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('moderator', models.IntegerField(blank=True, null=True)),
                ('show_date', models.DateField(blank=True, null=True)),
                ('show_time', models.TimeField(blank=True, null=True)),
                ('show_name', models.CharField(blank=True, max_length=100, null=True)),
                ('show_place', models.CharField(blank=True, max_length=100, null=True)),
                ('main_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowTopic',
            fields=[
                ('mm_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'show_topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'topics',
                'managed': False,
            },
        ),
    ]
