# Generated by Django 5.1.1 on 2024-10-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtopic',
            old_name='topic_count',
            new_name='is_main',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='main_topic',
        ),
    ]
