# Generated by Django 5.1.1 on 2024-09-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterModelOptions(
            name='showtopic',
            options={'verbose_name': 'м-м', 'verbose_name_plural': 'м-м'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={},
        ),
    ]
