# Generated by Django 5.1.1 on 2024-09-28 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shows_options_alter_showtopic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='showtopic',
            name='showw',
            field=models.ForeignKey(blank=True, db_column='showw', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.shows'),
        ),
        migrations.AddField(
            model_name='showtopic',
            name='topic',
            field=models.ForeignKey(blank=True, db_column='topic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.topics'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_shows', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='shows',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_shows', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='status',
            field=models.CharField(choices=[('active', 'Действует'), ('removed', 'Удалена')], default='active', max_length=100),
        ),
    ]
